### ISSUE TITLE
Understand problem

### ISSUE THREAD

**Issue by visualight** [kersten/node-dyndns-client#1]
Hello i try to use your dyndns client on a node server but i not understand how it work.
In the code below, where i must enter the username and password (in the URL AND in the options) ?
Why did you "double" the parameters (username, password, hostname, ... ?

Can you provide me a working demo example ?
If i take your code like this and change only the options between brackets (username, password, host) i get an error.

Thank you

var DynDNSClient = require("node-dyndns-client"),
    dyndns = new DynDNSClient({
        url                 : "http://[USERNAME]:[PASSWORD]@members.dyndns.org/nic/update?hostname=[HOSTNAME]&myip=[IP]",
        hostname            : [
            "test.dyndns.org",
            "customtest.dyndns.org"
        ],
        username            : 'username',
        password            : 'password',
        network_interface   : 'ppp0',
        protocol            : 'ipv4',
        check               : 60
    });

**Comment by kersten** [comment]
Hi @visualight,

could you have a look again? I just updated the code. Sorry for now examples etc, but I did not know that people really using ist ;) was a bit surprised about the download counts on npm.

Hope this helps, otherwise just tell me please what it says now. I do not have a dyndns account any more. Maybe this piece could get an update to support multiple dynamic dns services.

Greetings Kersten
